version: '3'

services:
  openmrs-reference-app:
    restart: "always"
    image: openmrs/openmrs-reference-application-distro:demo
    ports:
      - "8087:8080"
    environment:
      DB_DATABASE: 'openmrs'
      DB_HOST: openmrs-reference-mysql
      DB_USERNAME: 'root'
      DB_PASSWORD: 'Admin123'
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      MODULE_WEB_ADMIN: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - openmrs-reference-mysql-data:/usr/local/tomcat/.OpenMRS/
      - /usr/local/tomcat/.OpenMRS/modules/ # do not store modules in data
      - /usr/local/tomcat/.OpenMRS/owa/ # do not store owa in data

  openmrs-reference-mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: 'openmrs'
      MYSQL_ROOT_PASSWORD: 'Admin123'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Admin123'
    ports:
      - "3307:3306"
    healthcheck:
      test: "exit 0"
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
      - openmrs-reference-mysql-data:/var/lib/mysql

  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - cdr
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      - cdr
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - cdr
    ports:
      - "9000:80"
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  openmrs-reference-mysql-data:
  mongo-data:

networks:
  cdr:
