version: '3'

services: 
  #facilityA mysql
  openmrs-facilityA-mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: 'facilityA'
      MYSQL_ROOT_PASSWORD: 'Admin123'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Admin123'
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"
    volumes:
      - openmrs-facilityB-mysql-data:/var/lib/mysql
  
  #facilityA OpenMRS instance
  openmrs-facilityA:
    restart: "always"
    image: openmrs/openmrs-reference-application:${OPENMRS_VERSION:-qa}
    env_file:
      - path: ./config/.env
        required: true
    depends_on:
      - openmrs-facilityA-mysql
    ports:
      - "8086:8080"
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "false"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "false"
      OMRS_CONFIG_CONNECTION_SERVER: openmrs-facilityA-mysql
      OMRS_CONFIG_CONNECTION_URL: ${OPENMRS_DB_URL}
      OMRS_CONFIG_CONNECTION_DATABASE: 'facilityA'
      OMRS_CONFIG_CONNECTION_USERNAME: 'root'
      OMRS_CONFIG_CONNECTION_PASSWORD: 'Admin123'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/openmrs/" ]
      timeout: 20s

  #facilityB mysql
  openmrs-facilityB-mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: 'facilityB'
      MYSQL_ROOT_PASSWORD: 'Admin123'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Admin123'
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"
    volumes:
      - openmrs-facilityB-mysql-data:/var/lib/mysql
 
  #facilityB OpenMRS instance
  openmrs-facilityB:
    restart: "always"
    image: openmrs/openmrs-reference-application-distro:demo
    depends_on:
      - openmrs-facilityB-mysql
    ports:
      - "8082:8080"
    environment:
      DB_DATABASE: 'facilityB'
      DB_HOST: openmrs-facilityB-mysql
      DB_USERNAME: 'root'
      DB_PASSWORD: 'Admin123'
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      MODULE_WEB_ADMIN: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - openmrs-facilityB-mysql-data:/usr/local/tomcat/.OpenMRS/
      - /usr/local/tomcat/.OpenMRS/modules/ # do not store modules in data
      - /usr/local/tomcat/.OpenMRS/owa/ # do not store owa in data

  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - cdr
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      - cdr
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - cdr
    ports:
      - "9000:80"
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  openmrs-facilityA-mysql-data:
  openmrs-facilityB-mysql-data:
  mongo-data:

networks:
  cdr:
